### PR TITLE
No AUTH/TLS support, plain text body and subject, concourse build metadata

### LINKED ISSUE #6: SMTP username
Hi,

I'd like to integrate this email-resource on a development landscape. I do have access to an SMTP server there, but without user/password for authentication. I don't think I'd need username/password in a dedicated development landscape. 

Unfortunately with this plugin I have to provide username/password, and it does not works for my case. I'd be happy to see that feature. Or is that something that won't be supported as part of this resource?

Cheers,
Fabian

### PR DESCRIPTION
**Pull request by friegger**
We required a couple of features that have not been there yet. As we did quite some changes, this pull request is more about starting the discussion whether you are interested in such changes. Especially, as the PR contains some changes that are not backwards compatible, see below. We definitely would be able to create new pull requests, containing only parts of the features.

**Changes contain the following:**
- add option to send emails without AUTH and TLS. Also resolves #6.
- `body`/`subject` are now plain text, `body_file`/`subject_file` provide the former behavior. **Not backwards compatible**.
- `body` and `subject` support rendering of concourse build metadata, e.g. `${BUILD_NAME}`
- refactored code out of main packages to get better testability and type reuse

Please let us know what you think.

### CODE REVIEW

**Comment by cdevienne** [comment]
How about keeping subject and body for filenames and add subject_text and body_text for plain text ?

**Comment by alexander-matsievsky** [comment]
@friegger Would you be interested in that https://github.com/concourse/concourse/issues/1434?

**Comment by alexander-matsievsky** [comment]
Unfortunately, the fork is the only option,
https://github.com/concourse/concourse/issues/1434.

**Comment by calebwashburn** [comment]
@friegger Interested in some of these changes. Taking over this resource and want to get some of the changes included (and give credit for PR).  Can you resubmit as individual PR's as there are now merge conflicts and don't want to cherry pick your commits and not give credit?

**Comment by friegger** [comment]
@calebwashburn Which changes are you interested in? What's your opinion regarding `body/subject` and `body_file/subject_file`?

**Comment by calebwashburn** [comment]
@friegger I think it would be beneficial to have ability to specify text without a file for both body and subject.  In order to maintain backward compatibility can we introduce 2 new params (body_text and subject_text).  Where either subject or subject_text is required (same for body/body_text).  This would allow us to introduce this without breaking any existing consumers.

**Pull request closed without merging**
